name: trigger-demo
on:
  push:
    branches:
      - main
  pull_requests:
  workflow_dispatch:  

jobs:
  trigger-demo:
    runs-on: windows-latest
    steps:
        run: | 
          echo "Hello World"
      